# Generated by Django 3.0 on 2020-05-19 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='my_books',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AddField(
            model_name='my_books',
            name='tbublish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='my_books',
            name='content',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
