# Generated by Django 3.0 on 2020-05-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0002_auto_20200519_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_books',
            old_name='tbublish',
            new_name='tpublish',
        ),
    ]
